blank_issues_enabled: false
contact_links:
    - name: Question 🤷
      url: https://github.com/gemini-testing/html-reporter/discussions
      about: Ask questions and discuss with other community members
